node{
    docker.image('node:lts-alpine').inside {
        withEnv(['CI=true']) {
            stage('Build') {
                sh 'npm install'
            }
            stage('Test') {
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}
