node{
    docker.image('node:lts-alpine').inside('-p 3000:3000') {
        withEnv(['CI=true']) {
            stage('Build') {
                sh 'npm install'
            }
            stage('Test') {
                sh './jenkins/scripts/test.sh'
                echo 'Trying run the static web locally before proceed the deployment'
                sh './jenkins/scripts/deliver.sh'
                sh 'sleep 1m'
                sh './jenkins/scripts/kill.sh'
            }
            stage('Deploy') {
                input(message: 'Izinkan untuk melanjutkan deployment?', ok: 'Proceed')
                echo 'Deployment berhasil'
            }
        }
    }
}

// pipeline {
//     agent {
//         docker {
//             image 'node:lts-alpine'
//             args '-p 3000:3000'
//         }
//     }
    
//     environment {
//         CI = 'true'
//     }

//     stages {
//         stage ('Build') {
//             steps{
//                 sh 'npm install'
//             }
//         }
//         stage ('Test') {
//             steps{
//                 sh './jenkins/scripts/test.sh'
//             }
//         }
//         stage ('Deploy') {
//             steps{
//                 sh './jenkins/scripts/deliver.sh'
//                 sleep 10
//                 sh './jenkins/scripts/kill.sh'
//             }
//         }

//     }
// }